# Generated by Django 4.1.7 on 2023-03-10 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_alter_person_cpf_alter_person_data_nasc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='data_nasc',
            field=models.DateField(blank=True, null=True),
        ),
    ]
